### ISSUE TITLE
Namespace conflict with golang cookbook

### ISSUE THREAD

**Issue by mjuszczak** [gocd-contrib/go-cookbook#48]
Per https://github.com/NOX73/chef-golang/blob/master/attributes/default.rb#L1, both this cookbook and the golang cookbook are using node['go']['version']. We're researching a workaround on our end.

**Comment by Tpbrown** [comment]
We should probably change this to "gocd". 

Go-Lang is much more known. I assume that means we'll disrupt fewer people.

~Sent from my mobile device. Please pardon any oddities :-)

**Comment by mjuszczak** [comment]
Pull request opened! Please review :) Thanks!

**Comment by tomzo** [comment]
This is in master now. Root namespace is `gocd`
