### ISSUE TITLE
Allow static definition of server in agent config

### ISSUE THREAD

**Issue by miroswan** [gocd-contrib/go-cookbook#62]
This cookbook appears to assume that there would be only one Go server. If more than one server is found in the search, then it uses the first one found. If I want to allocate a go cd cluster per team, this would be problematic. 

Perhaps provide an attribute called node['gocd']['server'] and set to nil, consequently allowing users to set this value. If they don't, then have logic that falls back on existing search logic.

**Comment by tomzo** [comment]
This is not entirely true.

This cookbook does not support provisioning multiple servers - you'll have to setup those differently. 
But agents LWRP can have [go server host and port](https://github.com/gocd-contrib/go-cookbook/blob/develop/resources/agent.rb#L12) specified.

I believe the attribute you would want to have is `node['gocd']['agent']['go_server_host']` [here](https://github.com/gocd-contrib/go-cookbook/blob/develop/libraries/helpers.rb#L8)

But anyway you don't need an attribute in `gocd` cookbook. Instead I would recommend using go_agent lwrp like this
```ruby
gocd_agent 'my-go-agent' do
  go_server_host node[:wrapper_cookbook][:go_server]
  go_server_port 80
  ...
end
```

@miroswan Let me know if this fits your use case.

**Comment by miroswan** [comment]
This looks good. I was actually looking at master which looked a little different.
