### ISSUE TITLE
Releases should be tagged

### ISSUE THREAD

**Issue by miroswan** [gocd-contrib/go-cookbook#64]
Releases should be tagged so I can version pin in my Berksfile.

**Comment by miroswan** [comment]
[This might make releasing easier](https://github.com/miroswan/chef_git_deployer)

**Comment by tomzo** [comment]
@miroswan Thanks for the link. I tagged repository manually now. We will setup snap-ci to do releases automatically soon. Hopefully with upload to chef supermarket too

**Comment by miroswan** [comment]
Nice.
