### ISSUE TITLE
missing maintainer and maintainer_email metadata

### ISSUE THREAD

**Issue by darrin-wortlehock** [gocd-contrib/go-cookbook#72]
I can't upload this cookbook with berks upload to a new chef server. 

The server responds with: {"error":["Field 'metadata.maintainer' invalid"]}

This is an issue currently affecting many community cookbooks at present.

Please add maintainer and maintainer_email entries to metadata.rb to resolve this issue.

**Comment by alaa** [comment]
+1

**Comment by Paul2e** [comment]
+1
