### ISSUE TITLE
Chef supermarket metadata

### ISSUE THREAD

**Issue by naumchenko** [gocd-contrib/go-cookbook#84]
Seems that cookbook in Supermarket missing maintainer and email, but version is the same.
Please push stable build to supermarket! thx.

ERROR: cookbooks failed to write: HTTP error writing: 400 "Bad Request" cause: {"error":["Field 'metadata.maintainer_email' invalid"]}
ERROR: cookbooks failed to write: HTTP error writing: 400 "Bad Request" cause: {"error":["Field 'metadata.maintainer' invalid"]}

"maintainer":null,"maintainer_email":null,

**Comment by webframp** [comment]
:+1: 

This appears to have been fixed in ba900ffe298b7b18e4e3c037c06875e871ef2469 but no new release yet. Can we get a new point release out to the supermarket?

**Comment by tomzo** [comment]
There is `1.3.0` uploaded with maintainer info
