### ISSUE TITLE
Recommended server setup?

### ISSUE THREAD

**Issue by michaeloa** [gocd-contrib/go-cookbook#87]
What is the recommended way to setup GoCD server and agents? It seems like the agent cookbook here sets up 16? agents by default, which seems like a fair amount for a typical server. Should agents and server run on the same box, or seperate boxes.

For context, we're setting this up on an Openstack cloud, with 4 CPU, 8-GB RAM VMs as standard. Would it be best to have 1 VM for the server and 2-4 VMs for the agents, or would it make sense to install them all on the same VM. And how many agents per CPU?

**Comment by michaeloa** [comment]
Also thinking here in terms of how it would be easiest to scale out/up in future.

**Comment by tomzo** [comment]
Hi @michaeloa 

> It seems like the agent cookbook here sets up 16? agents by default

Where did you got that idea? The cookbook provides a resource for any number of agents you like.
Also you should try asking and searching for this type of problems on [gocd user forum](https://groups.google.com/forum/#!forum/go-cd). This is just a chef cookbook, less community here and we'd rather keep discussions related to chef operations.

I also doubt there is a rule of thumb, other than keep server separate from agents. You'll want to deploy (and break) agents more often. Size really depends on workload patterns, as you said. E.g. I run 3 flavors of agents.
