### ISSUE TITLE
Redundant init.d file for golang go-agent

### ISSUE THREAD

**Issue by xmik** [gocd-contrib/go-cookbook#90]
Installing golang Go-agent from Debian package provides [`/etc/init.d/gocd-golang-agent`](https://github.com/gocd-contrib/gocd-golang-agent/blob/master/installers/deb/package/etc/init.d/gocd-golang-agent) file. Gocd cookbook also provides [init.d file for golang go-agent](https://github.com/gocd-contrib/go-cookbook/blob/bf4cfe2e1a5d870af0e6f26c11b249fbc8fd89c3/templates/default/golang-agent-init.erb). When using Gocd cookbook and 2 golang Go-agents, there are such files available after provisioning:
* `/etc/init.d/gocd-golang-agent`
* `/etc/init.d/go-agent`
* `/etc/init.d/go-agent-1`

and `/etc/init.d/gocd-golang-agent` is redundant.

This issue is well resolved for java Go-agents: Go-agent Debian package provides [`/etc/init.d/go-agent`](https://github.com/gocd/gocd/blob/master/installers/go-agent/release/go-agent.init) file and then Gocd cookbook does this: https://github.com/gocd-contrib/go-cookbook/blob/bf4cfe2e1a5d870af0e6f26c11b249fbc8fd89c3/resources/agent.rb#L68 . I suggest the same way for golang Go-agents.

**Comment by tomzo** [comment]
Since 1.3.1 the golang-agent apt package is no longer used. We just download a binary and setup init scripts only via cookbook.
